name: Rails Coverage Comment with Minitest

on:
  pull_request:
    branches:
      - '*'

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install dependencies
        run: |
          bundle install

      - name: Setup database
        run: |
          bundle exec rails db:create
          bundle exec rails db:schema:load

      - name: Run tests with coverage
        run: |
          bundle exec rails test --format=JUnit --out=test-results.xml

      - name: Rails coverage comment
        uses: manishch1095/rails-coverage-comment@v1.0.0
        with:
          coverage-path: ./coverage/index.html
          test-results-path: ./test-results.xml
          title: 'Minitest Coverage Report'
          badge-title: 'Minitest Coverage' 