name: Test Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test Rails Coverage Comment Action
        uses: ./
        with:
          coverage-path: ./test-data/coverage/index.html
          test-results-path: ./test-data/test-results.xml
          hide-comment: true
          title: 'Test Coverage Report'
          badge-title: 'Test Coverage' 